version: "3.9"
services:
  api:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./nba.db:/app/nba.db
    command: ["gunicorn", "-c", "uvicorn.ini", "app.main:app"]

  web:
    build: ./frontend
    env_file: .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - api