FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml /app/
RUN pip install --no-cache-dir -U pip && \
    pip install --no-cache-dir -e .
COPY app /app/app
ENV PYTHONUNBUFFERED=1
EXPOSE 8000
CMD ["gunicorn", "-c", "uvicorn.ini", "app.main:app"]